"""
    key: assembly instruction
    value:
        format: Format of instruction. May be "1", "2", "3"
        code: Hex code of instruction.
        sic: Whether the instruction is supported by SIC or not.
"""
OPERATION = {
    "ADD": {"format": "3", "code": 0x18, "sic": True},
    "ADDF": {"format": "3", "code": 0x58, "sic": False},
    "ADDR": {"format": "2", "code": 0x90, "sic": False},
    "AND": {"format": "3", "code": 0x40, "sic": True},
    "CLEAR": {"format": "2", "code": 0xB4, "sic": False},
    "COMP": {"format": "3", "code": 0x28, "sic": True},
    "COMPF": {"format": "3", "code": 0x88, "sic": False},
    "COMPR": {"format": "2", "code": 0xA0, "sic": False},
    "DIV": {"format": "3", "code": 0x24, "sic": True},
    "DIVF": {"format": "3", "code": 0x64, "sic": False},
    "DIVR": {"format": "2", "code": 0x9C, "sic": False},
    "FIX": {"format": "1", "code": 0xC4, "sic": False},
    "FLOAT": {"format": "1", "code": 0xC0, "sic": False},
    "HIO": {"format": "1", "code": 0xF4, "sic": False},
    "J": {"format": "3", "code": 0x3C, "sic": True},
    "JEQ": {"format": "3", "code": 0x30, "sic": True},
    "JGT": {"format": "3", "code": 0x34, "sic": True},
    "JLT": {"format": "3", "code": 0x38, "sic": True},
    "JSUB": {"format": "3", "code": 0x48, "sic": True},
    "LDA": {"format": "3", "code": 0x0, "sic": True},
    "LDB": {"format": "3", "code": 0x68, "sic": False},
    "LDCH": {"format": "3", "code": 0x50, "sic": True},
    "LDF": {"format": "3", "code": 0x70, "sic": False},
    "LDL": {"format": "3", "code": 0x8, "sic": True},
    "LDS": {"format": "3", "code": 0x6C, "sic": False},
    "LDT": {"format": "3", "code": 0x74, "sic": False},
    "LDX": {"format": "3", "code": 0x4, "sic": True},
    "LPS": {"format": "3", "code": 0xD0, "sic": False},
    "MUL": {"format": "3", "code": 0x20, "sic": True},
    "MULF": {"format": "3", "code": 0x60, "sic": False},
    "MULR": {"format": "2", "code": 0x98, "sic": False},
    "NORM": {"format": "1", "code": 0xC8, "sic": False},
    "OR": {"format": "3", "code": 0x44, "sic": True},
    "RD": {"format": "3", "code": 0xD8, "sic": True},
    "RMO": {"format": "2", "code": 0xAC, "sic": False},
    "RSUB": {"format": "3", "code": 0x4C, "sic": True},
    "SHIFTL": {"format": "2", "code": 0xA4, "sic": False},
    "SHIFTR": {"format": "2", "code": 0xA8, "sic": False},
    "SIO": {"format": "1", "code": 0xF0, "sic": False},
    "SSK": {"format": "3", "code": 0xEC, "sic": False},
    "STA": {"format": "3", "code": 0xC, "sic": True},
    "STB": {"format": "3", "code": 0x78, "sic": False},
    "STCH": {"format": "3", "code": 0x54, "sic": True},
    "STF": {"format": "3", "code": 0x80, "sic": False},
    "STI": {"format": "3", "code": 0xD4, "sic": False},
    "STL": {"format": "3", "code": 0x14, "sic": True},
    "STS": {"format": "3", "code": 0x7C, "sic": False},
    "STSW": {"format": "3", "code": 0xE8, "sic": True},
    "STT": {"format": "3", "code": 0x84, "sic": False},
    "STX": {"format": "3", "code": 0x10, "sic": True},
    "SUB": {"format": "3", "code": 0x1C, "sic": True},
    "SUBF": {"format": "3", "code": 0x5C, "sic": False},
    "SUBR": {"format": "2", "code": 0x94, "sic": False},
    "SVC": {"format": "2", "code": 0xB0, "sic": False},
    "TD": {"format": "3", "code": 0xE0, "sic": True},
    "TIO": {"format": "1", "code": 0xF8, "sic": False},
    "TIX": {"format": "3", "code": 0x2C, "sic": True},
    "TIXR": {"format": "2", "code": 0xB8, "sic": False},
    "WD": {"format": "3", "code": 0xDC, "sic": True},
}
